### ISSUE TITLE
Are there Local records or plans to add that feature?

### ISSUE THREAD

**Issue by R0CKB0TT0M** [marek-stoj/Beat-Labs-Builds-Pico#1]
I was wondering if there's a way to save and show scores locally to compete for records with friends or if there are plans for such a feature?
Thanks for the great game by the way.

**Comment by marek-stoj** [comment]
Thanks for the kind words! There is no such feature implemented (yet). You might check out the Discord server and the #feature-requests channel, where you can put your ideas and vote for others': https://dsc.gg/beatlabs
